apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "session-manager.fullname" . }}-migrate
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
    app.kuberentes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "session-manager.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: {{ include "session-manager.name" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ template "session-manager.image" (tuple .Values.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.command }}
          command: {{ . }}
          {{- end }}
          args: [ "migrate" ]
          env: []
          volumeMounts:
            - name: {{ include "session-manager.name" . }}-config-volume
              mountPath: /etc/{{ include "session-manager.name" . }}
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "session-manager.name" . }}-config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "session-manager.name" . }}-config
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
